export type SurgeryRequestStatus = "Requested" | "Accepted" | "Scheduled" | "In OT" | "Completed" | "Deferred" | "Stopped";
export type SlotStatus = "Available" | "Scheduled" | "Wheeled in" | "Wheeled out" | "Completed" | "Stopped" | "Differed";

export type SurgeryRequest = {
  id: string;
  patientName: string;
  ageGender: string;
  mrn: string;
  requestedBy: string;
  chiefSurgeon: string;
  anesthetist: string;
  surgeryName: string;
  surgeryDate: string;
  surgeryTime: string;
  durationMinutes: number;
  instructions: string;
  status: SurgeryRequestStatus;
  priority: "Routine" | "Urgent" | "Emergency";
  service: string;
};

export type SurgeryFilter = {
  id: string;
  criteria: keyof Pick<SurgeryRequest, "patientName" | "mrn" | "requestedBy" | "chiefSurgeon" | "anesthetist" | "surgeryName" | "surgeryDate" | "status">;
  value: string;
};

export type OtRoom = {
  id: string;
  name: string;
  specialty: string;
};

export type OtBooking = {
  id: string;
  requestId: string;
  otId: string;
  time: string;
  date: string;
  status: SlotStatus;
};

const baseSurgeryRequests: SurgeryRequest[] = [
  {
    id: "srg-001",
    patientName: "Rohan Mehta",
    ageGender: "48/M",
    mrn: "MRN-284901",
    requestedBy: "Dr. Kavita Rao",
    chiefSurgeon: "Dr. Arvind Menon",
    anesthetist: "Dr. Sana Qureshi",
    surgeryName: "Laparoscopic cholecystectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "10:30",
    durationMinutes: 90,
    instructions: "NPO confirmed. Consent and PAC clearance required before wheeling in.",
    status: "Requested",
    priority: "Routine",
    service: "General Surgery",
  },
  {
    id: "srg-002",
    patientName: "Aarav Sharma",
    ageGender: "36/M",
    mrn: "MRN-112408",
    requestedBy: "Dr. Aman Verma",
    chiefSurgeon: "Dr. Prakash Iyer",
    anesthetist: "Dr. Neha Bedi",
    surgeryName: "ORIF radius fracture",
    surgeryDate: "23 May 2026",
    surgeryTime: "11:30",
    durationMinutes: 120,
    instructions: "Implant tray and C-arm availability to be confirmed.",
    status: "Accepted",
    priority: "Urgent",
    service: "Orthopedics",
  },
  {
    id: "srg-003",
    patientName: "Meera Iyer",
    ageGender: "62/F",
    mrn: "MRN-776521",
    requestedBy: "Dr. Farah Ali",
    chiefSurgeon: "Dr. Sameer Khan",
    anesthetist: "Dr. Ritu Sinha",
    surgeryName: "Craniotomy evacuation",
    surgeryDate: "23 May 2026",
    surgeryTime: "09:00",
    durationMinutes: 180,
    instructions: "Blood products arranged. ICU bed reserved.",
    status: "Scheduled",
    priority: "Emergency",
    service: "Neurosurgery",
  },
  {
    id: "srg-004",
    patientName: "Nisha Kapoor",
    ageGender: "29/F",
    mrn: "MRN-551210",
    requestedBy: "Dr. Nandini Shah",
    chiefSurgeon: "Dr. Leena Thomas",
    anesthetist: "Dr. Vivek Anand",
    surgeryName: "LSCS",
    surgeryDate: "23 May 2026",
    surgeryTime: "12:00",
    durationMinutes: 60,
    instructions: "Neonatal team to be informed. Crossmatch ready.",
    status: "Requested",
    priority: "Urgent",
    service: "Obstetrics",
  },
  {
    id: "srg-005",
    patientName: "Kabir Sethi",
    ageGender: "54/M",
    mrn: "MRN-662019",
    requestedBy: "Dr. Rakesh Pillai",
    chiefSurgeon: "Dr. Mohit Bansal",
    anesthetist: "Dr. Isha Malhotra",
    surgeryName: "Total knee replacement",
    surgeryDate: "23 May 2026",
    surgeryTime: "09:30",
    durationMinutes: 150,
    instructions: "Tranexamic acid protocol. Physiotherapy counselling completed.",
    status: "Scheduled",
    priority: "Routine",
    service: "Orthopedics",
  },
  {
    id: "srg-006",
    patientName: "Fatima Khan",
    ageGender: "41/F",
    mrn: "MRN-438775",
    requestedBy: "Dr. Parul Jain",
    chiefSurgeon: "Dr. Ananya Bose",
    anesthetist: "Dr. Karan Mehta",
    surgeryName: "Thyroidectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "10:00",
    durationMinutes: 105,
    instructions: "Vocal cord assessment documented. Calcium monitoring post-op.",
    status: "Scheduled",
    priority: "Routine",
    service: "ENT",
  },
  {
    id: "srg-007",
    patientName: "Devika Nair",
    ageGender: "33/F",
    mrn: "MRN-903118",
    requestedBy: "Dr. Vimal Roy",
    chiefSurgeon: "Dr. Sandeep Narang",
    anesthetist: "Dr. Mira Sen",
    surgeryName: "Diagnostic laparoscopy",
    surgeryDate: "23 May 2026",
    surgeryTime: "10:00",
    durationMinutes: 75,
    instructions: "Consent for possible conversion taken.",
    status: "Scheduled",
    priority: "Routine",
    service: "Gynecology",
  },
  {
    id: "srg-008",
    patientName: "Harsh Vardhan",
    ageGender: "67/M",
    mrn: "MRN-519284",
    requestedBy: "Dr. Shalini Gupta",
    chiefSurgeon: "Dr. Aditya Raman",
    anesthetist: "Dr. Pooja Arora",
    surgeryName: "CABG standby evaluation",
    surgeryDate: "23 May 2026",
    surgeryTime: "11:00",
    durationMinutes: 240,
    instructions: "Cardiac perfusion team on standby. Blood products reserved.",
    status: "Scheduled",
    priority: "Emergency",
    service: "Cardiac Surgery",
  },
  {
    id: "srg-009",
    patientName: "Anika Dutta",
    ageGender: "7/F",
    mrn: "MRN-774230",
    requestedBy: "Dr. Nikhil Das",
    chiefSurgeon: "Dr. Farhan Siddiqui",
    anesthetist: "Dr. Reema Thomas",
    surgeryName: "Appendectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "12:30",
    durationMinutes: 60,
    instructions: "Pediatric dose chart verified.",
    status: "Scheduled",
    priority: "Urgent",
    service: "Pediatric Surgery",
  },
  {
    id: "srg-010",
    patientName: "Suresh Patil",
    ageGender: "59/M",
    mrn: "MRN-120604",
    requestedBy: "Dr. Lalit Joshi",
    chiefSurgeon: "Dr. Gaurav Ahuja",
    anesthetist: "Dr. Neelam Wadhwa",
    surgeryName: "TURP",
    surgeryDate: "23 May 2026",
    surgeryTime: "13:00",
    durationMinutes: 80,
    instructions: "Irrigation fluids and resectoscope checked.",
    status: "Scheduled",
    priority: "Routine",
    service: "Urology",
  },
  {
    id: "srg-011",
    patientName: "Priya Menon",
    ageGender: "45/F",
    mrn: "MRN-663502",
    requestedBy: "Dr. Elina Roy",
    chiefSurgeon: "Dr. Varun Chawla",
    anesthetist: "Dr. Namrata Singh",
    surgeryName: "Modified radical mastectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "13:30",
    durationMinutes: 135,
    instructions: "Frozen section availability confirmed.",
    status: "Scheduled",
    priority: "Routine",
    service: "Oncosurgery",
  },
  {
    id: "srg-012",
    patientName: "Imran Qureshi",
    ageGender: "52/M",
    mrn: "MRN-305781",
    requestedBy: "Dr. Ritu Kapoor",
    chiefSurgeon: "Dr. Tapan Ghosh",
    anesthetist: "Dr. Armaan Gill",
    surgeryName: "VATS decortication",
    surgeryDate: "23 May 2026",
    surgeryTime: "14:00",
    durationMinutes: 160,
    instructions: "Double lumen tube arranged. ICU bed requested.",
    status: "Scheduled",
    priority: "Urgent",
    service: "Thoracic Surgery",
  },
  {
    id: "srg-013",
    patientName: "Lakshmi Rao",
    ageGender: "71/F",
    mrn: "MRN-887410",
    requestedBy: "Dr. Mehul Shah",
    chiefSurgeon: "Dr. Pankaj Kulkarni",
    anesthetist: "Dr. Simran Kaur",
    surgeryName: "Hip hemiarthroplasty",
    surgeryDate: "23 May 2026",
    surgeryTime: "14:30",
    durationMinutes: 120,
    instructions: "Cemented stem set ready. DVT prophylaxis ordered.",
    status: "Scheduled",
    priority: "Urgent",
    service: "Orthopedics",
  },
  {
    id: "srg-014",
    patientName: "Tara Singh",
    ageGender: "25/F",
    mrn: "MRN-249016",
    requestedBy: "Dr. Bhavna Lal",
    chiefSurgeon: "Dr. Raghav Suri",
    anesthetist: "Dr. Vidhi Shah",
    surgeryName: "Septoplasty",
    surgeryDate: "23 May 2026",
    surgeryTime: "15:00",
    durationMinutes: 70,
    instructions: "Nasal packs and endoscope checked.",
    status: "Scheduled",
    priority: "Routine",
    service: "ENT",
  },
  {
    id: "srg-015",
    patientName: "Yusuf Ali",
    ageGender: "39/M",
    mrn: "MRN-984612",
    requestedBy: "Dr. Karishma Taneja",
    chiefSurgeon: "Dr. Ashok Nambiar",
    anesthetist: "Dr. Heena Jacob",
    surgeryName: "Renal stone PCNL",
    surgeryDate: "23 May 2026",
    surgeryTime: "15:30",
    durationMinutes: 110,
    instructions: "Prone positioning checklist completed.",
    status: "Scheduled",
    priority: "Routine",
    service: "Urology",
  },
  {
    id: "srg-016",
    patientName: "Maya Banerjee",
    ageGender: "58/F",
    mrn: "MRN-745930",
    requestedBy: "Dr. Rohan Suri",
    chiefSurgeon: "Dr. Kunal Rastogi",
    anesthetist: "Dr. Alka Menon",
    surgeryName: "Hemicolectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "16:00",
    durationMinutes: 180,
    instructions: "ERAS protocol. Stoma therapist informed.",
    status: "Scheduled",
    priority: "Routine",
    service: "GI Surgery",
  },
  {
    id: "srg-017",
    patientName: "Neeraj Bhatia",
    ageGender: "46/M",
    mrn: "MRN-651044",
    requestedBy: "Dr. Satish Nair",
    chiefSurgeon: "Dr. Viraj Narula",
    anesthetist: "Dr. Noor Khan",
    surgeryName: "Spine decompression",
    surgeryDate: "23 May 2026",
    surgeryTime: "16:30",
    durationMinutes: 150,
    instructions: "Neuromonitoring team assigned.",
    status: "Scheduled",
    priority: "Urgent",
    service: "Neurosurgery",
  },
  {
    id: "srg-018",
    patientName: "Kavya Reddy",
    ageGender: "31/F",
    mrn: "MRN-508271",
    requestedBy: "Dr. Iqbal Hussain",
    chiefSurgeon: "Dr. Meera Balan",
    anesthetist: "Dr. Rishi Anand",
    surgeryName: "Ovarian cystectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "17:00",
    durationMinutes: 95,
    instructions: "Histopathology requisition prepared.",
    status: "Scheduled",
    priority: "Routine",
    service: "Gynecology",
  },
  {
    id: "srg-019",
    patientName: "Vikram Soni",
    ageGender: "64/M",
    mrn: "MRN-394820",
    requestedBy: "Dr. Saira Mir",
    chiefSurgeon: "Dr. Abhay Khanna",
    anesthetist: "Dr. Natasha Paul",
    surgeryName: "Emergency laparotomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "17:30",
    durationMinutes: 210,
    instructions: "Sepsis bundle active. Blood bank alerted.",
    status: "Scheduled",
    priority: "Emergency",
    service: "Trauma Surgery",
  },
  {
    id: "srg-020",
    patientName: "Reena George",
    ageGender: "50/F",
    mrn: "MRN-872611",
    requestedBy: "Dr. Manav Arora",
    chiefSurgeon: "Dr. Jayant Sood",
    anesthetist: "Dr. Anita Kurian",
    surgeryName: "Varicose vein ablation",
    surgeryDate: "23 May 2026",
    surgeryTime: "18:00",
    durationMinutes: 65,
    instructions: "Duplex marking done before shifting.",
    status: "Scheduled",
    priority: "Routine",
    service: "Vascular Surgery",
  },
];

export const otRooms: OtRoom[] = [
  { id: "ot-1", name: "OT 1", specialty: "General Surgery" },
  { id: "ot-2", name: "OT 2", specialty: "Orthopedics" },
  { id: "ot-3", name: "OT 3", specialty: "Neurosurgery" },
  { id: "ot-4", name: "OT 4", specialty: "Obstetrics" },
  { id: "ot-5", name: "OT 5", specialty: "Cardiac standby" },
  { id: "ot-6", name: "OT 6", specialty: "Emergency reserve" },
];

export const otTimes = [
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
];

export const surgeryRequests: SurgeryRequest[] = baseSurgeryRequests.map((request, index) => ({
  ...request,
  surgeryTime: "",
  status: index % 2 === 0 ? "Requested" : "Accepted",
}));

export const otBookings: OtBooking[] = [];
