export type SurgeryRequestStatus = "Requested" | "Accepted" | "Scheduled" | "In OT" | "Completed" | "Deferred" | "Stopped";
export type SlotStatus = "Available" | "Scheduled" | "Wheeled in" | "Wheeled out" | "Completed" | "Stopped" | "Differed";

export type SurgeryRequest = {
  id: string;
  patientName: string;
  ageGender: string;
  mrn: string;
  requestedBy: string;
  chiefSurgeon: string;
  anesthetist: string;
  surgeryName: string;
  surgeryDate: string;
  surgeryTime: string;
  durationMinutes: number;
  instructions: string;
  status: SurgeryRequestStatus;
  priority: "Routine" | "Urgent" | "Emergency";
  service: string;
};

export type SurgeryFilter = {
  id: string;
  criteria: keyof Pick<SurgeryRequest, "patientName" | "mrn" | "requestedBy" | "chiefSurgeon" | "anesthetist" | "surgeryName" | "surgeryDate" | "status">;
  value: string;
};

export type OtRoom = {
  id: string;
  name: string;
  specialty: string;
};

export type OtBooking = {
  id: string;
  requestId: string;
  otId: string;
  time: string;
  date: string;
  status: SlotStatus;
};

const baseSurgeryRequests: SurgeryRequest[] = [
  {
    id: "srg-001",
    patientName: "Rohan Mehta",
    ageGender: "48/M",
    mrn: "MRN-284901",
    requestedBy: "Dr. Kavita Rao",
    chiefSurgeon: "Dr. Arvind Menon",
    anesthetist: "Dr. Sana Qureshi",
    surgeryName: "Laparoscopic cholecystectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "10:30",
    durationMinutes: 90,
    instructions: "NPO confirmed. Consent and PAC clearance required before wheeling in.",
    status: "Requested",
    priority: "Routine",
    service: "General Surgery",
  },
  {
    id: "srg-002",
    patientName: "Aarav Sharma",
    ageGender: "36/M",
    mrn: "MRN-112408",
    requestedBy: "Dr. Aman Verma",
    chiefSurgeon: "Dr. Prakash Iyer",
    anesthetist: "Dr. Neha Bedi",
    surgeryName: "ORIF radius fracture",
    surgeryDate: "23 May 2026",
    surgeryTime: "11:30",
    durationMinutes: 120,
    instructions: "Implant tray and C-arm availability to be confirmed.",
    status: "Accepted",
    priority: "Urgent",
    service: "Orthopedics",
  },
  {
    id: "srg-003",
    patientName: "Meera Iyer",
    ageGender: "62/F",
    mrn: "MRN-776521",
    requestedBy: "Dr. Farah Ali",
    chiefSurgeon: "Dr. Sameer Khan",
    anesthetist: "Dr. Ritu Sinha",
    surgeryName: "Craniotomy evacuation",
    surgeryDate: "23 May 2026",
    surgeryTime: "09:00",
    durationMinutes: 180,
    instructions: "Blood products arranged. ICU bed reserved.",
    status: "Scheduled",
    priority: "Emergency",
    service: "Neurosurgery",
  },
  {
    id: "srg-004",
    patientName: "Nisha Kapoor",
    ageGender: "29/F",
    mrn: "MRN-551210",
    requestedBy: "Dr. Nandini Shah",
    chiefSurgeon: "Dr. Leena Thomas",
    anesthetist: "Dr. Vivek Anand",
    surgeryName: "LSCS",
    surgeryDate: "23 May 2026",
    surgeryTime: "12:00",
    durationMinutes: 60,
    instructions: "Neonatal team to be informed. Crossmatch ready.",
    status: "Requested",
    priority: "Urgent",
    service: "Obstetrics",
  },
  {
    id: "srg-005",
    patientName: "Kabir Sethi",
    ageGender: "54/M",
    mrn: "MRN-662019",
    requestedBy: "Dr. Rakesh Pillai",
    chiefSurgeon: "Dr. Mohit Bansal",
    anesthetist: "Dr. Isha Malhotra",
    surgeryName: "Total knee replacement",
    surgeryDate: "23 May 2026",
    surgeryTime: "09:30",
    durationMinutes: 150,
    instructions: "Tranexamic acid protocol. Physiotherapy counselling completed.",
    status: "Scheduled",
    priority: "Routine",
    service: "Orthopedics",
  },
  {
    id: "srg-006",
    patientName: "Fatima Khan",
    ageGender: "41/F",
    mrn: "MRN-438775",
    requestedBy: "Dr. Parul Jain",
    chiefSurgeon: "Dr. Ananya Bose",
    anesthetist: "Dr. Karan Mehta",
    surgeryName: "Thyroidectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "10:00",
    durationMinutes: 105,
    instructions: "Vocal cord assessment documented. Calcium monitoring post-op.",
    status: "Scheduled",
    priority: "Routine",
    service: "ENT",
  },
  {
    id: "srg-007",
    patientName: "Devika Nair",
    ageGender: "33/F",
    mrn: "MRN-903118",
    requestedBy: "Dr. Vimal Roy",
    chiefSurgeon: "Dr. Sandeep Narang",
    anesthetist: "Dr. Mira Sen",
    surgeryName: "Diagnostic laparoscopy",
    surgeryDate: "23 May 2026",
    surgeryTime: "10:00",
    durationMinutes: 75,
    instructions: "Consent for possible conversion taken.",
    status: "Scheduled",
    priority: "Routine",
    service: "Gynecology",
  },
  {
    id: "srg-008",
    patientName: "Harsh Vardhan",
    ageGender: "67/M",
    mrn: "MRN-519284",
    requestedBy: "Dr. Shalini Gupta",
    chiefSurgeon: "Dr. Aditya Raman",
    anesthetist: "Dr. Pooja Arora",
    surgeryName: "CABG standby evaluation",
    surgeryDate: "23 May 2026",
    surgeryTime: "11:00",
    durationMinutes: 240,
    instructions: "Cardiac perfusion team on standby. Blood products reserved.",
    status: "Scheduled",
    priority: "Emergency",
    service: "Cardiac Surgery",
  },
  {
    id: "srg-009",
    patientName: "Anika Dutta",
    ageGender: "7/F",
    mrn: "MRN-774230",
    requestedBy: "Dr. Nikhil Das",
    chiefSurgeon: "Dr. Farhan Siddiqui",
    anesthetist: "Dr. Reema Thomas",
    surgeryName: "Appendectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "12:30",
    durationMinutes: 60,
    instructions: "Pediatric dose chart verified.",
    status: "Scheduled",
    priority: "Urgent",
    service: "Pediatric Surgery",
  },
  {
    id: "srg-010",
    patientName: "Suresh Patil",
    ageGender: "59/M",
    mrn: "MRN-120604",
    requestedBy: "Dr. Lalit Joshi",
    chiefSurgeon: "Dr. Gaurav Ahuja",
    anesthetist: "Dr. Neelam Wadhwa",
    surgeryName: "TURP",
    surgeryDate: "23 May 2026",
    surgeryTime: "13:00",
    durationMinutes: 80,
    instructions: "Irrigation fluids and resectoscope checked.",
    status: "Scheduled",
    priority: "Routine",
    service: "Urology",
  },
  {
    id: "srg-011",
    patientName: "Priya Menon",
    ageGender: "45/F",
    mrn: "MRN-663502",
    requestedBy: "Dr. Elina Roy",
    chiefSurgeon: "Dr. Varun Chawla",
    anesthetist: "Dr. Namrata Singh",
    surgeryName: "Modified radical mastectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "13:30",
    durationMinutes: 135,
    instructions: "Frozen section availability confirmed.",
    status: "Scheduled",
    priority: "Routine",
    service: "Oncosurgery",
  },
  {
    id: "srg-012",
    patientName: "Imran Qureshi",
    ageGender: "52/M",
    mrn: "MRN-305781",
    requestedBy: "Dr. Ritu Kapoor",
    chiefSurgeon: "Dr. Tapan Ghosh",
    anesthetist: "Dr. Armaan Gill",
    surgeryName: "VATS decortication",
    surgeryDate: "23 May 2026",
    surgeryTime: "14:00",
    durationMinutes: 160,
    instructions: "Double lumen tube arranged. ICU bed requested.",
    status: "Scheduled",
    priority: "Urgent",
    service: "Thoracic Surgery",
  },
  {
    id: "srg-013",
    patientName: "Lakshmi Rao",
    ageGender: "71/F",
    mrn: "MRN-887410",
    requestedBy: "Dr. Mehul Shah",
    chiefSurgeon: "Dr. Pankaj Kulkarni",
    anesthetist: "Dr. Simran Kaur",
    surgeryName: "Hip hemiarthroplasty",
    surgeryDate: "23 May 2026",
    surgeryTime: "14:30",
    durationMinutes: 120,
    instructions: "Cemented stem set ready. DVT prophylaxis ordered.",
    status: "Scheduled",
    priority: "Urgent",
    service: "Orthopedics",
  },
  {
    id: "srg-014",
    patientName: "Tara Singh",
    ageGender: "25/F",
    mrn: "MRN-249016",
    requestedBy: "Dr. Bhavna Lal",
    chiefSurgeon: "Dr. Raghav Suri",
    anesthetist: "Dr. Vidhi Shah",
    surgeryName: "Septoplasty",
    surgeryDate: "23 May 2026",
    surgeryTime: "15:00",
    durationMinutes: 70,
    instructions: "Nasal packs and endoscope checked.",
    status: "Scheduled",
    priority: "Routine",
    service: "ENT",
  },
  {
    id: "srg-015",
    patientName: "Yusuf Ali",
    ageGender: "39/M",
    mrn: "MRN-984612",
    requestedBy: "Dr. Karishma Taneja",
    chiefSurgeon: "Dr. Ashok Nambiar",
    anesthetist: "Dr. Heena Jacob",
    surgeryName: "Renal stone PCNL",
    surgeryDate: "23 May 2026",
    surgeryTime: "15:30",
    durationMinutes: 110,
    instructions: "Prone positioning checklist completed.",
    status: "Scheduled",
    priority: "Routine",
    service: "Urology",
  },
  {
    id: "srg-016",
    patientName: "Maya Banerjee",
    ageGender: "58/F",
    mrn: "MRN-745930",
    requestedBy: "Dr. Rohan Suri",
    chiefSurgeon: "Dr. Kunal Rastogi",
    anesthetist: "Dr. Alka Menon",
    surgeryName: "Hemicolectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "16:00",
    durationMinutes: 180,
    instructions: "ERAS protocol. Stoma therapist informed.",
    status: "Scheduled",
    priority: "Routine",
    service: "GI Surgery",
  },
  {
    id: "srg-017",
    patientName: "Neeraj Bhatia",
    ageGender: "46/M",
    mrn: "MRN-651044",
    requestedBy: "Dr. Satish Nair",
    chiefSurgeon: "Dr. Viraj Narula",
    anesthetist: "Dr. Noor Khan",
    surgeryName: "Spine decompression",
    surgeryDate: "23 May 2026",
    surgeryTime: "16:30",
    durationMinutes: 150,
    instructions: "Neuromonitoring team assigned.",
    status: "Scheduled",
    priority: "Urgent",
    service: "Neurosurgery",
  },
  {
    id: "srg-018",
    patientName: "Kavya Reddy",
    ageGender: "31/F",
    mrn: "MRN-508271",
    requestedBy: "Dr. Iqbal Hussain",
    chiefSurgeon: "Dr. Meera Balan",
    anesthetist: "Dr. Rishi Anand",
    surgeryName: "Ovarian cystectomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "17:00",
    durationMinutes: 95,
    instructions: "Histopathology requisition prepared.",
    status: "Scheduled",
    priority: "Routine",
    service: "Gynecology",
  },
  {
    id: "srg-019",
    patientName: "Vikram Soni",
    ageGender: "64/M",
    mrn: "MRN-394820",
    requestedBy: "Dr. Saira Mir",
    chiefSurgeon: "Dr. Abhay Khanna",
    anesthetist: "Dr. Natasha Paul",
    surgeryName: "Emergency laparotomy",
    surgeryDate: "23 May 2026",
    surgeryTime: "17:30",
    durationMinutes: 210,
    instructions: "Sepsis bundle active. Blood bank alerted.",
    status: "Scheduled",
    priority: "Emergency",
    service: "Trauma Surgery",
  },
  {
    id: "srg-020",
    patientName: "Reena George",
    ageGender: "50/F",
    mrn: "MRN-872611",
    requestedBy: "Dr. Manav Arora",
    chiefSurgeon: "Dr. Jayant Sood",
    anesthetist: "Dr. Anita Kurian",
    surgeryName: "Varicose vein ablation",
    surgeryDate: "23 May 2026",
    surgeryTime: "18:00",
    durationMinutes: 65,
    instructions: "Duplex marking done before shifting.",
    status: "Scheduled",
    priority: "Routine",
    service: "Vascular Surgery",
  },
  {
    id: "srg-021",
    patientName: "Aditi Kulkarni",
    ageGender: "42/F",
    mrn: "MRN-610284",
    requestedBy: "Dr. Sneha Desai",
    chiefSurgeon: "Dr. Nikhil Batra",
    anesthetist: "Dr. Radhika Jain",
    surgeryName: "Laparoscopic appendectomy",
    surgeryDate: "24 May 2026",
    surgeryTime: "09:00",
    durationMinutes: 70,
    instructions: "Antibiotic dose charted. Pregnancy test negative and consent verified.",
    status: "Requested",
    priority: "Urgent",
    service: "General Surgery",
  },
  {
    id: "srg-022",
    patientName: "Manish Agarwal",
    ageGender: "56/M",
    mrn: "MRN-731905",
    requestedBy: "Dr. Rakesh Pillai",
    chiefSurgeon: "Dr. Mohit Bansal",
    anesthetist: "Dr. Isha Malhotra",
    surgeryName: "Arthroscopic ACL reconstruction",
    surgeryDate: "24 May 2026",
    surgeryTime: "09:30",
    durationMinutes: 140,
    instructions: "Sports implant set and tourniquet checked. Physiotherapy briefing completed.",
    status: "Accepted",
    priority: "Routine",
    service: "Orthopedics",
  },
  {
    id: "srg-023",
    patientName: "Zoya Mirza",
    ageGender: "34/F",
    mrn: "MRN-408172",
    requestedBy: "Dr. Parul Jain",
    chiefSurgeon: "Dr. Ananya Bose",
    anesthetist: "Dr. Karan Mehta",
    surgeryName: "Tonsillectomy",
    surgeryDate: "24 May 2026",
    surgeryTime: "10:00",
    durationMinutes: 55,
    instructions: "Bleeding risk reviewed. Post-op airway observation bed reserved.",
    status: "Requested",
    priority: "Routine",
    service: "ENT",
  },
  {
    id: "srg-024",
    patientName: "Ritesh Choudhary",
    ageGender: "63/M",
    mrn: "MRN-926347",
    requestedBy: "Dr. Shalini Gupta",
    chiefSurgeon: "Dr. Aditya Raman",
    anesthetist: "Dr. Pooja Arora",
    surgeryName: "AV fistula creation",
    surgeryDate: "24 May 2026",
    surgeryTime: "10:30",
    durationMinutes: 85,
    instructions: "Left arm marked. Dialysis schedule reviewed with nephrology.",
    status: "Accepted",
    priority: "Routine",
    service: "Vascular Surgery",
  },
  {
    id: "srg-025",
    patientName: "Sunita Yadav",
    ageGender: "47/F",
    mrn: "MRN-184560",
    requestedBy: "Dr. Karishma Taneja",
    chiefSurgeon: "Dr. Ashok Nambiar",
    anesthetist: "Dr. Heena Jacob",
    surgeryName: "Ureteroscopic lithotripsy",
    surgeryDate: "24 May 2026",
    surgeryTime: "11:00",
    durationMinutes: 95,
    instructions: "Laser fiber and DJ stent available. Urine culture reviewed.",
    status: "Requested",
    priority: "Urgent",
    service: "Urology",
  },
  {
    id: "srg-026",
    patientName: "Neil Fernandes",
    ageGender: "28/M",
    mrn: "MRN-503918",
    requestedBy: "Dr. Aman Verma",
    chiefSurgeon: "Dr. Prakash Iyer",
    anesthetist: "Dr. Neha Bedi",
    surgeryName: "Meniscus repair",
    surgeryDate: "24 May 2026",
    surgeryTime: "11:30",
    durationMinutes: 100,
    instructions: "Arthroscopy tower booked. MRI films uploaded to PACS.",
    status: "Accepted",
    priority: "Routine",
    service: "Orthopedics",
  },
  {
    id: "srg-027",
    patientName: "Bhavna Trivedi",
    ageGender: "52/F",
    mrn: "MRN-367294",
    requestedBy: "Dr. Elina Roy",
    chiefSurgeon: "Dr. Varun Chawla",
    anesthetist: "Dr. Namrata Singh",
    surgeryName: "Wide local excision breast lump",
    surgeryDate: "24 May 2026",
    surgeryTime: "12:00",
    durationMinutes: 90,
    instructions: "Wire localization planned. Histopathology requisition printed.",
    status: "Requested",
    priority: "Routine",
    service: "Oncosurgery",
  },
  {
    id: "srg-028",
    patientName: "Omkar Joshi",
    ageGender: "44/M",
    mrn: "MRN-819406",
    requestedBy: "Dr. Satish Nair",
    chiefSurgeon: "Dr. Viraj Narula",
    anesthetist: "Dr. Noor Khan",
    surgeryName: "Microdiscectomy",
    surgeryDate: "24 May 2026",
    surgeryTime: "12:30",
    durationMinutes: 125,
    instructions: "Prone positioning supports ready. Neuromonitoring consent signed.",
    status: "Accepted",
    priority: "Urgent",
    service: "Neurosurgery",
  },
  {
    id: "srg-029",
    patientName: "Esha Malhotra",
    ageGender: "38/F",
    mrn: "MRN-247631",
    requestedBy: "Dr. Iqbal Hussain",
    chiefSurgeon: "Dr. Meera Balan",
    anesthetist: "Dr. Rishi Anand",
    surgeryName: "Hysteroscopic polypectomy",
    surgeryDate: "24 May 2026",
    surgeryTime: "13:00",
    durationMinutes: 65,
    instructions: "Fluid deficit monitoring chart prepared.",
    status: "Requested",
    priority: "Routine",
    service: "Gynecology",
  },
  {
    id: "srg-030",
    patientName: "Girish Nambiar",
    ageGender: "61/M",
    mrn: "MRN-690582",
    requestedBy: "Dr. Rohan Suri",
    chiefSurgeon: "Dr. Kunal Rastogi",
    anesthetist: "Dr. Alka Menon",
    surgeryName: "Laparoscopic hernia repair",
    surgeryDate: "24 May 2026",
    surgeryTime: "13:30",
    durationMinutes: 115,
    instructions: "Mesh size confirmed. Diabetes peri-op orders reviewed.",
    status: "Accepted",
    priority: "Routine",
    service: "GI Surgery",
  },
  {
    id: "srg-031",
    patientName: "Pallavi Saxena",
    ageGender: "35/F",
    mrn: "MRN-572018",
    requestedBy: "Dr. Nandini Shah",
    chiefSurgeon: "Dr. Leena Thomas",
    anesthetist: "Dr. Vivek Anand",
    surgeryName: "Dilatation and curettage",
    surgeryDate: "24 May 2026",
    surgeryTime: "14:00",
    durationMinutes: 45,
    instructions: "Consent includes histopathology. Rh status checked.",
    status: "Requested",
    priority: "Urgent",
    service: "Obstetrics",
  },
  {
    id: "srg-032",
    patientName: "Rahul Bendre",
    ageGender: "49/M",
    mrn: "MRN-145739",
    requestedBy: "Dr. Lalit Joshi",
    chiefSurgeon: "Dr. Gaurav Ahuja",
    anesthetist: "Dr. Neelam Wadhwa",
    surgeryName: "Cystoscopy and bladder biopsy",
    surgeryDate: "24 May 2026",
    surgeryTime: "14:30",
    durationMinutes: 75,
    instructions: "Biopsy bottles labelled. Anticoagulant hold documented.",
    status: "Accepted",
    priority: "Routine",
    service: "Urology",
  },
  {
    id: "srg-033",
    patientName: "Ishita Basu",
    ageGender: "16/F",
    mrn: "MRN-984207",
    requestedBy: "Dr. Nikhil Das",
    chiefSurgeon: "Dr. Farhan Siddiqui",
    anesthetist: "Dr. Reema Thomas",
    surgeryName: "Pediatric herniotomy",
    surgeryDate: "24 May 2026",
    surgeryTime: "15:00",
    durationMinutes: 60,
    instructions: "Guardian consent verified. Pediatric airway cart available.",
    status: "Requested",
    priority: "Routine",
    service: "Pediatric Surgery",
  },
  {
    id: "srg-034",
    patientName: "Jatin Arora",
    ageGender: "57/M",
    mrn: "MRN-430861",
    requestedBy: "Dr. Saira Mir",
    chiefSurgeon: "Dr. Abhay Khanna",
    anesthetist: "Dr. Natasha Paul",
    surgeryName: "Debridement and external fixation",
    surgeryDate: "24 May 2026",
    surgeryTime: "15:30",
    durationMinutes: 130,
    instructions: "Emergency consent noted. Blood bank and implant vendor informed.",
    status: "Accepted",
    priority: "Emergency",
    service: "Trauma Surgery",
  },
  {
    id: "srg-035",
    patientName: "Kritika Jain",
    ageGender: "30/F",
    mrn: "MRN-761294",
    requestedBy: "Dr. Bhavna Lal",
    chiefSurgeon: "Dr. Raghav Suri",
    anesthetist: "Dr. Vidhi Shah",
    surgeryName: "Functional endoscopic sinus surgery",
    surgeryDate: "24 May 2026",
    surgeryTime: "16:00",
    durationMinutes: 110,
    instructions: "CT PNS reviewed. Navigation system request placed.",
    status: "Requested",
    priority: "Routine",
    service: "ENT",
  },
  {
    id: "srg-036",
    patientName: "Samar Khan",
    ageGender: "68/M",
    mrn: "MRN-602913",
    requestedBy: "Dr. Farah Ali",
    chiefSurgeon: "Dr. Sameer Khan",
    anesthetist: "Dr. Ritu Sinha",
    surgeryName: "Burr hole drainage",
    surgeryDate: "24 May 2026",
    surgeryTime: "16:30",
    durationMinutes: 100,
    instructions: "Repeat CT reviewed. ICU step-down bed requested.",
    status: "Accepted",
    priority: "Emergency",
    service: "Neurosurgery",
  },
  {
    id: "srg-037",
    patientName: "Minal Shah",
    ageGender: "55/F",
    mrn: "MRN-258470",
    requestedBy: "Dr. Mehul Shah",
    chiefSurgeon: "Dr. Pankaj Kulkarni",
    anesthetist: "Dr. Simran Kaur",
    surgeryName: "Ankle fracture fixation",
    surgeryDate: "24 May 2026",
    surgeryTime: "17:00",
    durationMinutes: 115,
    instructions: "Swelling status reassessed. C-arm slot confirmed.",
    status: "Requested",
    priority: "Urgent",
    service: "Orthopedics",
  },
  {
    id: "srg-038",
    patientName: "Adnan Sheikh",
    ageGender: "46/M",
    mrn: "MRN-375620",
    requestedBy: "Dr. Ritu Kapoor",
    chiefSurgeon: "Dr. Tapan Ghosh",
    anesthetist: "Dr. Armaan Gill",
    surgeryName: "Pleural biopsy",
    surgeryDate: "24 May 2026",
    surgeryTime: "17:30",
    durationMinutes: 80,
    instructions: "Single lung ventilation plan discussed. Chest drain set ready.",
    status: "Accepted",
    priority: "Routine",
    service: "Thoracic Surgery",
  },
  {
    id: "srg-039",
    patientName: "Tanvi Rao",
    ageGender: "27/F",
    mrn: "MRN-846159",
    requestedBy: "Dr. Vimal Roy",
    chiefSurgeon: "Dr. Sandeep Narang",
    anesthetist: "Dr. Mira Sen",
    surgeryName: "Laparoscopic endometriosis excision",
    surgeryDate: "24 May 2026",
    surgeryTime: "18:00",
    durationMinutes: 145,
    instructions: "Consent for adhesiolysis recorded. Ureteric stent standby noted.",
    status: "Requested",
    priority: "Routine",
    service: "Gynecology",
  },
  {
    id: "srg-040",
    patientName: "Pranav Sinha",
    ageGender: "72/M",
    mrn: "MRN-519763",
    requestedBy: "Dr. Manav Arora",
    chiefSurgeon: "Dr. Jayant Sood",
    anesthetist: "Dr. Anita Kurian",
    surgeryName: "Peripheral angioplasty access support",
    surgeryDate: "24 May 2026",
    surgeryTime: "18:30",
    durationMinutes: 90,
    instructions: "Renal function reviewed. Contrast allergy checklist completed.",
    status: "Accepted",
    priority: "Urgent",
    service: "Vascular Surgery",
  },
  {
    id: "srg-041",
    patientName: "Naveen Kumar",
    ageGender: "40/M",
    mrn: "MRN-704825",
    requestedBy: "Dr. Kavita Rao",
    chiefSurgeon: "Dr. Arvind Menon",
    anesthetist: "Dr. Sana Qureshi",
    surgeryName: "Open inguinal hernia repair",
    surgeryDate: "25 May 2026",
    surgeryTime: "09:00",
    durationMinutes: 85,
    instructions: "Spinal anesthesia plan. Mesh and antibiotic prophylaxis confirmed.",
    status: "Requested",
    priority: "Routine",
    service: "General Surgery",
  },
  {
    id: "srg-042",
    patientName: "Rachna Bhat",
    ageGender: "60/F",
    mrn: "MRN-132947",
    requestedBy: "Dr. Mehul Shah",
    chiefSurgeon: "Dr. Pankaj Kulkarni",
    anesthetist: "Dr. Simran Kaur",
    surgeryName: "Shoulder arthroplasty",
    surgeryDate: "25 May 2026",
    surgeryTime: "09:30",
    durationMinutes: 160,
    instructions: "Implant sizes checked. Regional block consent completed.",
    status: "Accepted",
    priority: "Routine",
    service: "Orthopedics",
  },
  {
    id: "srg-043",
    patientName: "Ayan Bose",
    ageGender: "12/M",
    mrn: "MRN-658214",
    requestedBy: "Dr. Nikhil Das",
    chiefSurgeon: "Dr. Farhan Siddiqui",
    anesthetist: "Dr. Reema Thomas",
    surgeryName: "Circumcision",
    surgeryDate: "25 May 2026",
    surgeryTime: "10:00",
    durationMinutes: 45,
    instructions: "Guardian present. Pediatric fasting status verified.",
    status: "Requested",
    priority: "Routine",
    service: "Pediatric Surgery",
  },
  {
    id: "srg-044",
    patientName: "Farida Ansari",
    ageGender: "51/F",
    mrn: "MRN-940371",
    requestedBy: "Dr. Elina Roy",
    chiefSurgeon: "Dr. Varun Chawla",
    anesthetist: "Dr. Namrata Singh",
    surgeryName: "Sentinel lymph node biopsy",
    surgeryDate: "25 May 2026",
    surgeryTime: "10:30",
    durationMinutes: 95,
    instructions: "Nuclear medicine timing confirmed. Blue dye allergy checked.",
    status: "Accepted",
    priority: "Routine",
    service: "Oncosurgery",
  },
  {
    id: "srg-045",
    patientName: "Harini Subramanian",
    ageGender: "43/F",
    mrn: "MRN-286503",
    requestedBy: "Dr. Parul Jain",
    chiefSurgeon: "Dr. Ananya Bose",
    anesthetist: "Dr. Karan Mehta",
    surgeryName: "Parotidectomy",
    surgeryDate: "25 May 2026",
    surgeryTime: "11:00",
    durationMinutes: 150,
    instructions: "Facial nerve monitor requested. Consent includes nerve risk discussion.",
    status: "Requested",
    priority: "Routine",
    service: "ENT",
  },
  {
    id: "srg-046",
    patientName: "Lalit Oberoi",
    ageGender: "66/M",
    mrn: "MRN-715896",
    requestedBy: "Dr. Farah Ali",
    chiefSurgeon: "Dr. Sameer Khan",
    anesthetist: "Dr. Ritu Sinha",
    surgeryName: "VP shunt placement",
    surgeryDate: "25 May 2026",
    surgeryTime: "11:30",
    durationMinutes: 135,
    instructions: "Shunt system available. Antibiotic prophylaxis and CT reviewed.",
    status: "Accepted",
    priority: "Urgent",
    service: "Neurosurgery",
  },
  {
    id: "srg-047",
    patientName: "Sneha Patankar",
    ageGender: "32/F",
    mrn: "MRN-369014",
    requestedBy: "Dr. Iqbal Hussain",
    chiefSurgeon: "Dr. Meera Balan",
    anesthetist: "Dr. Rishi Anand",
    surgeryName: "Myomectomy",
    surgeryDate: "25 May 2026",
    surgeryTime: "12:00",
    durationMinutes: 150,
    instructions: "Two units crossmatched. Fertility-preserving consent documented.",
    status: "Requested",
    priority: "Routine",
    service: "Gynecology",
  },
  {
    id: "srg-048",
    patientName: "Arjun Gill",
    ageGender: "58/M",
    mrn: "MRN-802746",
    requestedBy: "Dr. Ritu Kapoor",
    chiefSurgeon: "Dr. Tapan Ghosh",
    anesthetist: "Dr. Armaan Gill",
    surgeryName: "Bronchoscopy with biopsy",
    surgeryDate: "25 May 2026",
    surgeryTime: "12:30",
    durationMinutes: 70,
    instructions: "Coagulation profile normal. Cytology technician informed.",
    status: "Accepted",
    priority: "Urgent",
    service: "Thoracic Surgery",
  },
  {
    id: "srg-049",
    patientName: "Deepa Narayan",
    ageGender: "69/F",
    mrn: "MRN-475108",
    requestedBy: "Dr. Rohan Suri",
    chiefSurgeon: "Dr. Kunal Rastogi",
    anesthetist: "Dr. Alka Menon",
    surgeryName: "Open cholecystectomy",
    surgeryDate: "25 May 2026",
    surgeryTime: "13:00",
    durationMinutes: 130,
    instructions: "High-risk consent completed. ICU observation requested.",
    status: "Requested",
    priority: "Urgent",
    service: "GI Surgery",
  },
  {
    id: "srg-050",
    patientName: "Vivek Tandon",
    ageGender: "53/M",
    mrn: "MRN-627390",
    requestedBy: "Dr. Saira Mir",
    chiefSurgeon: "Dr. Abhay Khanna",
    anesthetist: "Dr. Natasha Paul",
    surgeryName: "Exploratory laparotomy",
    surgeryDate: "25 May 2026",
    surgeryTime: "13:30",
    durationMinutes: 200,
    instructions: "Emergency pathway active. Blood products and ICU bed arranged.",
    status: "Accepted",
    priority: "Emergency",
    service: "Trauma Surgery",
  },
];

export const otRooms: OtRoom[] = [
  { id: "ot-1", name: "OT 1", specialty: "General Surgery" },
  { id: "ot-2", name: "OT 2", specialty: "Orthopedics" },
  { id: "ot-3", name: "OT 3", specialty: "Neurosurgery" },
  { id: "ot-4", name: "OT 4", specialty: "Obstetrics" },
  { id: "ot-5", name: "OT 5", specialty: "Cardiac standby" },
  { id: "ot-6", name: "OT 6", specialty: "Emergency reserve" },
];

export const otTimes = [
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
];

export const surgeryRequests: SurgeryRequest[] = baseSurgeryRequests.map((request, index) => ({
  ...request,
  surgeryTime: "",
  status: index % 2 === 0 ? "Requested" : "Accepted",
}));

export const otBookings: OtBooking[] = [];
